---
title: "Results of the virtual privilege walk"
author: "Anne Cori"
date: "2023-10-31"
output: powerpoint_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r get_data, include = FALSE}
use_simulated_data = FALSE # TRUE
source("visualise_results.R")
```

## How diverse are we?
```{r diversity_pie, include = TRUE, fig.asp=1, dpi=300}
par(mar = c(3, 3, 3, 3))
pie(table(data_sorted$gender_ethnicity_no_na)[c(1, 2, 4, 3)],
    col = c(col_f, col_m, col_m_dark, col_f_dark))
```

## Does it vary by career stage?
```{r diversity_by_gender_and_career_stage, include = TRUE, fig.asp=0.35, dpi=300, fig.width = 11}
par(mar = c(2.5, 5, .5, 1.5), mfrow = c(1, 2))

# gender
plot(seq_along(job_levs), rep(0, length(job_levs)), col = "white", ylim = c(0, 1),
     xlab = "", ylab = "Proportion of females", axes = FALSE)
axis(side = 1, at = seq_along(job_levs), labels = job_levs_names, tick = FALSE, cex.axis = 0.8)
axis(side = 2, cex.axis = 0.8)
for(i in seq_along(job_levs)){
  p <- get_prop_f(data_sorted, job_levs[i])
  if(!is.na(p[1]))
  {
    if (i == 1) 
    {
      pch <- 18
      cex <- 4
      lwd <- 6
    }else
    {
      pch <- 19
      cex <- 1.5
      lwd <- 3
    }
    points(i, p[1], pch = pch, col = col_f, cex = cex)
    segments(i, p[2], i, p[3], col = col_f, lwd = lwd)
  }
}
abline(h = .5, col = "grey", lty = 2)

# ethnicity
plot(seq_along(job_levs), rep(0, length(job_levs)), col = "white", ylim = c(0, 1),
     xlab = "", ylab = "Proportion ethnic minority", axes = FALSE)
axis(side = 1, at = seq_along(job_levs), labels = job_levs_names, tick = FALSE, cex.axis = 0.8)
axis(side = 2, cex.axis = 0.8)
for(i in seq_along(job_levs)){
  p <- get_prop_nw(data_sorted, job_levs[i])
  if(!is.na(p[1]))
  {
    if (i == 1) 
    {
      pch <- 18
      cex <- 4
      lwd <- 6
    }else
    {
      pch <- 19
      cex <- 1.5
      lwd <- 3
    }
    points(i, p[1], pch = pch, cex = cex)
    segments(i, p[2], i, p[3], lwd = lwd)
  }
}
abline(h = .5, col = "grey", lty = 2)
```

## How privileged are we?

```{r privilege_overview, include = TRUE, fig.asp=0.5, dpi=300, fig.width = 10}
par(xpd = FALSE)
par(mfrow = c(1, 1), mar = c(.5, 4, 3, .5))
plot(seq_len(nrow(data_sorted_white_non_white_known_gender)), data_sorted_white_non_white_known_gender$rescaled_score, axes = FALSE,
     xlab = "Respondents", ylab = "",
     #ylim = c(-n_q, n_q), # previously when questions were +/-1 points
     ylim = c(0, n_q),
     pch = data_sorted_white_non_white_known_gender$pch,
     col = alpha(data_sorted_white_non_white_known_gender$col, 0.5),
     lwd = 2, cex = 1.5)
#abline(h = c(0, n_q, -n_q), lty = 2) # previously when questions were +/-1 points
abline(h = c(0, n_q, n_q/2), lty = 2)
axis(side = 2, at = seq(-n_q, n_q), labels = seq(-n_q, n_q)) # previously when questions were +/-1 points
axis(side = 2, at = seq(0, n_q), labels = seq(0, n_q))

mtext("Increasing privilege", side = 2, line = 3, col = "red", cex = 1.5)
par(xpd = TRUE)
mylims <- par("usr")
x <- mylims[1]
arrows(x, -1, x, n_q+1.5, length = 0.15, angle = 30,
       code = 2, col = "red", lwd = 3)
par(xpd = FALSE)

legend("bottomright", c("Student", "Postdoc", "Academic"),
       pch = c(16, 15, 17),
       pt.cex = 1.5, pt.lwd = 2,
       text.col = rep("black", 3),
       col = rep("black", 3),
       bg = rep("white", 3),
       box.lwd = 0, box.col = "white", bty = "o")

# add info on gender and ethnicity
for(i in c(gender_ethnicity, "ZOther/NA\nEthnic minority", "ZOther/NA\nWhite")) {
  tmp <- which(data_sorted_white_non_white_known_gender$gender_ethnicity %in% i)
  if(length(tmp) > 0) {
    if(i == gender_ethnicity[1]){
      abline(v = range(tmp), col = "grey")
    } else{
      abline(v = max(range(tmp)), col = "grey")
    }
  }
}

par(xpd = TRUE)
for(i in gender_ethnicity) {
  tmp <- which(data_sorted_white_non_white_known_gender$gender_ethnicity %in% i)
  if(length(tmp) > 0) {
    x <- mean(range(tmp))
    y <- 1.1 * n_q
    text(x, y, i, cex = 1.2)
  }
}

i <- "ZOther/NA\nEthnic minority"
tmp <- which(data_sorted_white_non_white_known_gender$gender_ethnicity %in% i)
if(length(tmp) > 0) {
  x <- mean(range(tmp))
  y <- 1.15 * n_q
  text(x, y, "Other Em", cex = 1.2)
}
i <- "ZOther/NA\nWhite"
tmp <- which(data_sorted_white_non_white_known_gender$gender_ethnicity %in% i)
if(length(tmp) > 0) {
  x <- mean(range(tmp))
  y <- 1.1 * n_q
  text(x, y, "Other W", cex = 1.1)
}
par(xpd = FALSE)

```

## Does it vary by gender/ethnicity/career stage?

```{r privilege_by_gender_ethnicity, include = TRUE, fig.asp=0.4, dpi=300, fig.width = 15}
par(mfrow = c(1, 2), mgp=c(3,2,0), mar = c(5, 5, 1, 1))

data_sorted$gender_ethnicity_no_na_reordered <- factor(data_sorted$gender_ethnicity_no_na , levels=c("Female\nEthnic minority", "Female\nWhite", "Male\nEthnic minority", "Male\nWhite"))

# distribution of privilege by gender and ethnicity
boxplot(rescaled_score ~ gender_ethnicity_no_na_reordered, data = data_sorted,
        col = c(col_f_dark, col_f, col_m_dark, col_m),
        xlab = "", ylab = "",
        #ylim = c(-n_q, n_q),
        ylim = c(0, n_q),
        frame = FALSE)
#abline(h = c(0, n_q, -n_q), col = "grey", lty = 2)
abline(h = c(0, n_q, n_q/2), col = "grey", lty = 2)

mtext("Increasing privilege", side = 2, line = 4, col = "red", cex = 1.5)
par(xpd = TRUE)
mylims <- par("usr")
x <- mylims[1]
arrows(x, -1, x, n_q+.5, length = 0.15, angle = 30,
       code = 2, col = "red", lwd = 3)
par(xpd = FALSE)

# distribution of privilege by career stage
boxplot(rescaled_score ~ job_no_na, data = data_sorted,
        xlab = "", ylab = "",
        #ylim = c(-n_q, n_q),
        ylim = c(0, n_q),
        frame = FALSE)
#abline(h = c(0, n_q, -n_q), col = "grey", lty = 2)
abline(h = c(0, n_q, n_q/2), col = "grey", lty = 2)

## TODO: possibly add Other gender to the boxplots 
## don't mix Other and NA for Gender
```


